package com.acn.wildlifeextractor.domain.enums;

public enum Action {
    NA, SMOKED_AND_NEST_REMOVED, NEST_REMOVED, CARBARYL_ADDED, DIATOMACEOUS_EARTH_ADDED,
    EGGS_DISPATCHED, CHICKS_DISPATCHED, ADULTS_DISPATCHED, ADULTS_REMOVED,
    RINGINGMORPHS_ADDED, SIGHTING_ADDED, SPECIES_ADDED, PHYSICAL_CONDITION_ADDED, OTHER
}
