package com.acn.wildlifeextractor.domain.enums;

public enum Behaviour {
    NA, UNK, ALONE_NO_BREEDING_BEHAVIOUR, ALONE_BREEDING_BEHAVIOUR,
    WITH_ANOTHER_BIRD_NO_BREEDING_BEHAVIOUR, WITH_ANOTHER_BIRD_BREEDING_BEHAVIOUR,
    PARENT_OFFSPRING_INTERACTIONS, INTERACTING_WITH_OFFSPRING, OTHER
}
