package com.acn.wildlifeextractor.domain.enums;

public enum ClinicalSigns {
    NA, DULL_FEATHERS, FEATHERS_PUFFED, MISSING_FEATHERS, YELLOW_FEATHERS, MALNOURISHED,
    DEHYDRATED, SCABS_LESIONS_ON_HEAD_BEAK, SCABS_LESIONS_ON_LEGS_FEET,
    SCABS_AND_WART_LIKE_LESIONS_ON_LEGS, MISSING_TOES, WHITE_YELLOW_LESIONS_IN_GAPE,
    WHITE_YELLOW_LESIONS_ON_EYE, OTHER
}
