package com.acn.wildlifeextractor.domain.enums;

public enum Impact {
    NA, UNK, NO_OBVIOUS_IMPACT,
    BREEDING_SPECIES_OF_INTEREST_DELAYED_ENTERING_NEST,
    BREEDING_SPECIES_OF_INTEREST_DELAYED_LEAVING_NEST,
    BREEDING_SPECIES_OF_INTEREST_CANT_ACCESS_NEST,
    SPECIES_OF_INTEREST_CHASING_COMPETITOR,
    BREEDING_SPECIES_OF_INTEREST_CHASING_COMPETITOR,
    SPECIES_OF_INTEREST_FIGHTING_COMPETITOR,
    BREEDING_SPECIES_OF_INTEREST_FIGHTING_COMPETITOR,
    PREDATION_DESTRUCTION_OF_NEST_CONTENTS, OTHER
}
