package com.acn.wildlifeextractor.domain.enums;

public enum ItemDescription {
    UNK, NECTAR, FLOWER, FLOWER_BUD, YOUNG_LEAF, LEAF, DEAD_LEAF,
    FRUIT, FRUIT_RIPE, FRUIT_UNRIPE, SEED, STEM, BARK,
    PHELSUMA_SPP, PHELSUMA_CEPEDIANA, PHELSUMA_ORNATA, PHELSUMA_GUMBEAUI, PHELSUMA_ROSAGULARIS,
    HOUSE_GECKO, AGAMID_LIZARD, GREY_WHITE_EYE, MADAGASCAR_FODY, RED_WHISKERED_BULBUL,
    COMMON_WAXBILL, ZEBRA_DOVE, YELLOW_FRONTED_CANARY, ASIAN_MUSK_SHREW, BLACK_RAT, BROWN_RAT,
    ODONATA_DRAGONFLY, PHASMATODEA_STICK_INSECT, HEMIPTERA_CICADA, OTHER,
    HYMENOPTERA_ANT, HYMENOPTERA_BEE, COLEOPTERA_BEETLE, HEMIPTERA_BUG,
    LEPIDOPTERA_BUTTERFLY, LEPIDOPTERA_CATERPILLAR, BLATTODEA_COCKROACH,
    ORTHOPTERA_CRICKET, DIPTERA_FLY, DIPTERA_LARVAE, LEPIDOPTERA_MOTH,
    MANTODEA_PRAYING_MANTIDS, ARACHNIDS_SPIDER, HYMENOPTERA_WASP
}
