package com.acn.wildlifeextractor.domain.enums;

public enum PurposeOfVisit {
    OPPORTUNISTIC, PRE_SEASON, EGG_CHECK, HATCH_CHECK, RINGING, MAINTENANCE,
    IDENTIFYING_PAIR, NEST_WATCH, BLEEDING, BLEEDING_AND_RINGING,
    FLEDGE_CHECK, PRE_FLEDGE_CHECK, OTHER
}
