package com.acn.wildlifeextractor.domain.enums;

public enum SpeciesEcho {
    ANTS, ECHO_PARAKEET, HONEY_BEE, INDIAN_MYNAH, INDIAN_WOLF_SNAKE,
    LONG_TAILED_MACAQUE, MAURITIUS_BULBUL, MAURITIUS_KRESTEL,
    PAPER_WASP, RAT, RAT_BLACK, RAT_BROWN,
    RING_NECKED_PARAKEET, SMALL_INDIAN_MONGOOSE, WHITE_TAILED_TROPIC_BIRD, OTHER
}
